#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Symbol-Global-Name
Version  : 0.05
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/A/AL/ALEXMV/Symbol-Global-Name-0.05.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AL/ALEXMV/Symbol-Global-Name-0.05.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libsymbol-global-name-perl/libsymbol-global-name-perl_0.05-1.debian.tar.xz
Summary  : 'finds name and type of a global variable'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Symbol-Global-Name-man
Requires: perl(Module::Install)
BuildRequires : perl(Module::Install)

%description
NAME
Symbol::Global::Name - finds name and type of a global variable
SYNOPSIS
package My;
our $VERSION = '0.1';

%package man
Summary: man components for the perl-Symbol-Global-Name package.
Group: Default

%description man
man components for the perl-Symbol-Global-Name package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Symbol-Global-Name-0.05
mkdir -p %{_topdir}/BUILD/Symbol-Global-Name-0.05/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Symbol-Global-Name-0.05/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Symbol/Global/Name.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Symbol::Global::Name.3
